# Generated by Django 2.1.7 on 2019-05-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbID', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rated', models.CharField(max_length=20)),
                ('released', models.DateField()),
                ('runtime', models.IntegerField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('poster', models.TextField()),
                ('rating', models.TextField()),
                ('imdbscore', models.DecimalField(decimal_places=1, max_digits=2)),
                ('production', models.CharField(max_length=30)),
                ('Genre', models.ManyToManyField(related_name='genre_movies', to='movie.Genre')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_movie', to='movie.Score'),
        ),
    ]
