# Generated by Django 2.1.7 on 2019-05-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_movie', to='movie.Score'),
        ),
    ]
