# Generated by Django 2.1.7 on 2019-05-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('rated', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('poster', models.TextField()),
                ('imdbID', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=100)),
                ('imdbScore', models.CharField(max_length=100)),
                ('trailer', models.TextField()),
                ('trailer_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('netflix_url', models.TextField()),
                ('year', models.CharField(max_length=100)),
                ('rated', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('actors', models.CharField(max_length=100)),
                ('trailer', models.TextField()),
                ('thumbnail', models.TextField()),
            ],
        ),
    ]
