# Generated by Django 2.1.7 on 2019-05-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('weak', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbID', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rated', models.CharField(blank=True, max_length=20, null=True)),
                ('released', models.DateField()),
                ('runtime', models.IntegerField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('poster', models.TextField()),
                ('ratings', models.TextField()),
                ('imdbRating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('production', models.CharField(max_length=30)),
                ('Genre', models.ManyToManyField(related_name='genre_movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_movie', to='movies.Score'),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Country'),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
